BasePath: I:\

FileNames:
 ColorSpacePerception: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Color-Space-Perception[BUFFER].activation.csv
 ColorSpaceAttention: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Attention-Color-Binding-Field[BUFFER].activation.csv
 CameraImage: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Camera_TCP_Reader[OUTPUT].output.csv
 ColorAttention: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Color-Attention-Field[BUFFER].activation.csv
 SpaceAttention: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Space-Attention-Field[BUFFER].activation.csv
 ColorConcepts: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\ObjectColor_Concepts[BUFFER].activation.csv
 SoundPerception: data\DFT-Architecture\Experiment_2022_04_19__16_12_00\Trial_0\Sound_Concepts[BUFFER].activation.csv
 histogramms: data\Simulation\Simulation_2022_04_19__16_11_36\actionCount.dat
 events: data\Simulation\Simulation_2022_04_19__16_11_36\events.dat
 trajectories: data\Simulation\Simulation_2022_04_19__16_11_36\trajectorie.dat